### ISSUE TITLE
Can't import

### ISSUE THREAD

**Issue by minhquan1313** [ZviadMestvi/units-converter-ts#1]
![image](https://github.com/ZviadMestvi/units-converter-ts/assets/20660062/316dd3b3-7798-48f0-bb10-435c4095b4c0)
![image](https://github.com/ZviadMestvi/units-converter-ts/assets/20660062/d02123e5-7fe8-454c-aa74-d37adefe9460)

**Comment by ZviadMestvi** [comment]
Sorry it took so long, but I was busy with other things. This issue should be fixed in the latest version. Please let me know if that is the case. If not can you tell me what stack are you using?
